### ISSUE TITLE
force close & screen orientation

### ISSUE THREAD

**Issue by flowardnut** [talklittle/reddit-is-fun#168]
Droid 1 running 2.3.4. (Bugless beast version)

If I have the option set to force portrait orientation, and have the keyboard slid out (which usually forces landscape) the app has a lot of troubles.

It force closes while trying to load comments.

**Comment by talklittle** [comment]
Unfortunately I cannot reproduce this Droid 1 Android 2.2.2, but I do
see a ton of Force Close reports on Android Market, so I'll definitely
look into it ASAP. Thanks for bringing this to my attention. Hopefully
the issue and fix are related to what I am seeing on Market:

java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:257)
at java.util.ArrayList.get(ArrayList.java:311)
at com.andrewshu.android.redditdonation.comments.CommentsListActivity.getOpThingInfo(CommentsListActivity.java:497)
at com.andrewshu.android.redditdonation.comments.CommentsListActivity.markSubmitterComments(CommentsListActivity.java:598)
at com.andrewshu.android.redditdonation.comments.DownloadCommentsTask.onPostExecute(DownloadCommentsTask.java:608)
at com.andrewshu.android.redditdonation.comments.DownloadCommentsTask.onPostExecute(DownloadCommentsTask.java:1)
at android.os.AsyncTask.finish(AsyncTask.java:417)
at android.os.AsyncTask.access$300(AsyncTask.java:127)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:429)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3683)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)

On Thu, Aug 11, 2011 at 7:17 PM, flowardnut
reply@reply.github.com
wrote:

**Comment by talklittle** [comment]
I fixed the bug that caused the crash that I pasted in previous comment. Hopefully it fixes the reported bug with portrait orientation too.
