### ISSUE TITLE
Force Close on Android 1.5 going to Comments

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#59]
Some users say only for comments over 200?

I think it's Sense UI problem. Unfortunately I can't test this on the emulator...

**Comment by talklittle** [comment]
still persists after 0.9.3a

**Comment by talklittle** [comment]
damn. StackOverFlowError when parsing deep comment hierarchies. need to rewrite parseCommentsJSON()

stack trace:

```
05-12 07:18:50.271 E/AndroidRuntime( 7621): java.lang.RuntimeException: An error occured while executing doInBackground()
05-12 07:18:50.271 E/AndroidRuntime( 7621): at android.os.AsyncTask$3.done(AsyncTask.java:200)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:234)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:258)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at java.util.concurrent.FutureTask.run(FutureTask.java:122)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:648)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:673)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at java.lang.Thread.run(Thread.java:1058)
05-12 07:18:50.271 E/AndroidRuntime( 7621): Caused by: java.lang.StackOverflowError
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.sym.BytesToNameCanonicalizer.findName(BytesToNameCanonicalizer.java:393)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.impl.Utf8StreamParser.findName(Utf8StreamParser.java:759)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.impl.Utf8StreamParser.parseMediumFieldName(Utf8StreamParser.java:346)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.impl.Utf8StreamParser._parseFieldName(Utf8StreamParser.java:309)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:145)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:384)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:286)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:135)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:221)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:390)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:286)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:135)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:221)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:390)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:286)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:135)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:221)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:390)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:286)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.ArrayDeserializer.deserialize(ArrayDeserializer.java:93)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:135)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:221)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:390)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:286)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:135)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:221)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:390)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:286)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:135)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:221)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:390)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:286)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:135)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:221)
05-12 07:18:50.271 E/AndroidRuntime( 7621): at org.codehaus.jackson.map.deser.BeanDese
```

**Comment by talklittle** [comment]
right now I'm very tempted to just drop support for Android 1.5 since that seems to be the problem.

I don't feel like going back and writing streaming JSON parsing support. definitely doable, but such an annoyance if it's just the old Android version that causes it, and presumably they should receive a new Android version soon.

**Comment by talklittle** [comment]
Sprint HTC Hero is receiving official OTA updates to Android 2.1! I'm dropping support for 1.5.
